name: Update vaccination_data.json

on:
#  schedule:
#    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Python requests
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Download new data
      run: python get_and_update.py
    
    - name: Add and commit new data
      uses: EndBug/add-and-commit@v7
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'vaccination_data.json'
        # The message for the commit
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Update vaccination_data.json'
